export const AGREGANDO_PRODUCTO = "AGREGANDO_PRODUCTO";
export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const PRODUCTO_AGREGADO = "PRODUCTO AGREGADO";

export const REMOVIENDO_PRODUCTO = "REMOVIENDO_PRODUCTO";
export const REMOVER_PRODUCTO = "REMOVER_PRODUCTO";
export const PRODUCTO_REMOVIDO = "PRODUCTO_REMOVIDO";

export const INCREMENTAR_CANTIDAD = "INCREMENTAR_CANTIDAD";
export const DECREMENTAR_CANTIDAD = "DECREMENTAR_CANTIDAD";

export const FINALIZANDO_COMPRA = "FINALIZANDO_COMPRA";
export const FINALIZAR_COMPRA = "FINALIZAR_COMPRA";
export const COMPRA_FINALIZADA = "COMPRA_FINALIZADA";
